### ISSUE TITLE
Hello, why this cannot be built.

### ISSUE THREAD

**Issue by bisectracky** [twosson/fildr-cli#5]
when I try to run (with proxy already on)
`go run build.go build`
it turns out to be 
`go: finding github.com/sirupsen/logrus v1.2.0
go: golang.org/x/tools@v0.0.0-20191029190741-b9c20aec41a5: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543: unrecognized import path "golang.org/x/xerrors" (https fetch: Get https://golang.org/x/xerrors?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/onsi/gomega v1.9.0
go: golang.org/x/sys@v0.0.0-20190422165155-953cdadca894: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/lint@v0.0.0-20190930215403-16217165b5de: unrecognized import path "golang.org/x/lint" (https fetch: Get https://golang.org/x/lint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/mod@v0.0.0-20190513183733-4bf6d317e70e: unrecognized import path "golang.org/x/mod" (https fetch: Get https://golang.org/x/mod?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20190411185658-b44545bcd369: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20200106162015-b016eb3dc98e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/time@v0.0.0-20191024005414-555d28b269f0: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: golang.org/x/sys@v0.0.0-20181116152217-5ac8a444bdc5: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20190626221950-04f50cda93cb: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20200615200032-f1bc736245b1: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/pkg/errors v0.8.0
go: golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: golang.org/x/net@v0.0.0-20181114220301-adae6a3d119a: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: golang.org/x/sys@v0.0.0-20190826190057-c7b8b68b1456: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: github.com/pkg/errors@v0.8.0: git -c protocol.version=0 fetch --unshallow -f https://github.com/pkg/errors refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/9b57de15915a2564a133192909d2d779433a38d49df7d581dc764e6764a41406: exit status 128:
	fatal: 无法访问 'https://github.com/pkg/errors/'：gnutls_handshake() failed: The TLS connection was non-properly terminated.
go: finding github.com/libp2p/go-libp2p-testing v0.0.3
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/go-kit/kit v0.8.0
go: finding github.com/onsi/ginkgo v1.12.1
go: golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/gogo/protobuf v1.1.1
go: golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: google.golang.org/api@v0.25.0: unrecognized import path "google.golang.org/api" (https fetch: Get https://google.golang.org/api?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/ipfs/go-ipfs-ds-help v0.0.1
go: finding gopkg.in/errgo.v2 v2.1.0
go: github.com/gogo/protobuf@v1.1.1: unknown revision v1.1.1
go: finding github.com/lucas-clemente/quic-go v0.16.0
go: golang.org/x/sys@v0.0.0-20190902133755-9109b7679e13: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/crypto@v0.0.0-20200423211502-4bdfaf469ed5: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: gopkg.in/errgo.v2@v2.1.0: unknown revision v2.1.0
go: github.com/lucas-clemente/quic-go@v0.16.0: unknown revision v0.16.0
go: github.com/ipfs/go-ipfs-ds-help@v0.0.1: git -c protocol.version=0 fetch --unshallow -f https://github.com/ipfs/go-ipfs-ds-help refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/e4ce55a0148672e1a9f1af0df2c91babf93af6101975939910253d1a76947c73: exit status 128:
	fatal: 无法访问 'https://github.com/ipfs/go-ipfs-ds-help/'：gnutls_handshake() failed: The TLS connection was non-properly terminated.
go: github.com/onsi/gomega@v1.9.0: unknown revision v1.9.0`

**Comment by twosson** [comment]
Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)  
Your network can't connect to Google Library
